import { ServerThemeProvider } from "next-themes";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import "./globals.css";
import { Providers } from "./providers";
import Portal from "./components/Portals/Portal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ServerThemeProvider>
      <html lang="en">
        <body>
          <Providers>
            <div id="myportal" />

            <Navbar />
            <main>{children}</main>
            <Footer />
          </Providers>
        </body>
      </html>
    </ServerThemeProvider>
  );
}
